services:
  streamlit:
    container_name: streamlit_app
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    # release 모드에서는 코드 마운트 ❌ (빌드 산출물 덮어씀)
    volumes:
      - ./data:/app/cube_data:ro
    environment:
      - SUPERSET_EMBED_COMPONENT_RELEASE=1
      - SUPERSET_PUBLIC_URL=http://localhost:8088
      - SUPERSET_INTERNAL_URL=http://superset_app:8088
      - SUPERSET_USERNAME=admin
      - SUPERSET_PASSWORD=admin
      - SUPERSET_EMBED_UUID=2aa226b5-10e3-47a7-bc81-d4796cd55a06
      - SUPERSET_GUEST_AUD=superset
      # - SUPERSET_DASHBOARD_ID=12
    networks:
      - agent4olap_net

networks:
  agent4olap_net:
    name: agent4olap_net
    external: true
