services:
  streamlit:
    container_name: streamlit_app
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/cube_data:ro
      - ./streamlit-app:/app
      - ./src:/app/src:ro
    working_dir: /app
    command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501 --server.runOnSave true
    environment:
      - SUPERSET_EMBED_COMPONENT_RELEASE=1
      - SUPERSET_PUBLIC_URL=http://localhost:8088
      - SUPERSET_INTERNAL_URL=http://superset_app:8088
      - FASTAPI_INTERNAL_URL=http://api:8000
      - FASTAPI_PUBLIC_URL=http://localhost:8000
      - FASTAPI_PUBLIC_URL=http://localhost:8000
      - SUPERSET_USERNAME=harry_potter
      - SUPERSET_PASSWORD=1234
      - SUPERSET_GUEST_AUD=superset
    networks:
      - agent4olap_net

networks:
  agent4olap_net:
    name: agent4olap_net
    external: true
