tpcds:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('TPCDS_DB_PATH') }}"
      database: tpcds
      schema: main
      threads: 4

    prod:
      type: duckdb
      path: "{{ env_var('TPCDS_DB_PATH') }}"
      threads: 4
