services:
  cube:
    container_name: tutorial
    image: cubejs/cube:latest
    user: "0:0" 
    ports:
      - 34000:4000
      - 35432:15432
    environment:
      - CUBEJS_DB_TYPE=duckdb
      - CUBEJS_DB_DUCKDB_DATABASE_PATH=/cube/data/tutorial.db
      - CUBEJS_DEV_MODE=true
      - CUBEJS_API_SECRET=secret
      - CUBEJS_TESSERACT_SQL_PLANNER=true

      - CUBEJS_PG_SQL_PORT=15432          # 컨테이너 내부 포트
      - CUBEJS_SQL_USER=user1     # 원하는 ID
      - CUBEJS_SQL_PASSWORD=Noel1999   # 원하는 PW
    volumes:
      - ./data/tutorial:/cube/data
      - ./cube_conf/tutorial:/cube/conf