services:
  cube:
    container_name: tpcds
    image: cubejs/cube:latest
    user: "${UID}:${GID}"
    ports:
      - 34000:4000
      - 35432:15432
    environment:
      - CUBEJS_DB_TYPE=duckdb
      - CUBEJS_DB_DUCKDB_DATABASE_PATH=/cube/data/tpcds.db
      - CUBEJS_DEV_MODE=true
      - CUBEJS_API_SECRET=secret
      - CUBEJS_TESSERACT_SQL_PLANNER=true
    volumes:
      - ./data/tpcds:/cube/data
      - ./cube_conf/tpcds:/cube/conf